comment-summary-in-pr: always

# Possible values: "critical", "high", "moderate", "low"
fail-on-severity: high

# # ([String]). Block the pull request on these licenses (optional)
# Possible values: Any SPDX-compliant license identifiers or expressions from https://spdx.org/licenses/
deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
