name: "Reusable Action 1"
description: "A simple reusable action that prints a custom message"
inputs:
  name:
    description: "Name to greet"
    required: true
    default: "World"
runs:
  using: "composite"
  steps:
    - name: Print Greeting
      shell: bash  # Define the shell to use for the command
      run: echo "Hello, ${{ inputs.name }}!"
