# Comprehensive GitHub Actions Workflow
# Simplified for displaying messages and learning purposes.

name: Comprehensive GitHub Actions Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom_param:
        description: 'Custom parameter for manual run'
        required: false
        default: 'default_value'

env:
  # Global environment variable accessible across all jobs
  GLOBAL_VAR: global_value

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: build_value
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 1  # Limit to one OS at a time
    steps:
      - name: Print Debug Information
        # Outputs system and environment information
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Global Variable: $GLOBAL_VAR"
          echo "Build Environment Variable: $BUILD_ENV"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"

  reusable_example:
    name: Call Reusable Workflow
    uses: ./.github/workflows/reusable.yml
    with:
      param1: 'Hello, reusable workflow!'
      param2: 'Optional value'
    secrets:
      API_SECRET: ${{ secrets.DEPLOY_API_KEY }}

  cleanup:
    name: Cleanup Job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Run Cleanup Scripts
        run: echo "Cleaning up after workflow..."
