# Comprehensive GitHub Actions Workflow
# Simplified for displaying messages and learning purposes.

name: Comprehensive GitHub Actions Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom_param:
        description: 'Custom parameter for manual run'
        required: false
        default: 'default_value'

env:
  # Global environment variable accessible across all jobs
  GLOBAL_VAR: global_value

permissions:
  contents: write
  actions: read
  checks: read

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: build_value
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      max-parallel: 1  # Limit to one OS at a time
    steps:
      - name: Print Debug Information
        # Outputs system and environment information
        run: |
          echo "Running on OS: ${{ matrix.os }}"
          echo "Global Variable: $GLOBAL_VAR"
          echo "Build Environment Variable: $BUILD_ENV"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"

  reusable_workflow_1:
    name: Call Reusable Workflow with Params 1
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      param1: 'First reusable workflow call'
      param2: 'Additional context for call 1'
    secrets:
      API_SECRET: ${{ secrets.DEPLOY_API_KEY }}

  reusable_workflow_2:
    name: Call Reusable Workflow with Params 2
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      param1: 'Second reusable workflow call'
      param2: 'Additional context for call 2'
    secrets:
      API_SECRET: ${{ secrets.DEPLOY_API_KEY }}

  reusable_action_1:
    name: Call Reusable Action 1 with Params 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Reusable Action 1 - Call 1
        uses: ./.github/actions/reusable-action-1
        with:
          name: "First Action Learner"

  reusable_action_2:
    name: Call Reusable Action 1 with Params 2
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Reusable Action 1 - Call 2
        uses: ./.github/actions/reusable-action-1
        with:
          name: "Second Action Learner"

  cleanup:
    name: Cleanup Job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Run Cleanup Scripts
        run: echo "Cleaning up after workflow..."
