# training workflow utilising as many components as possible
name: Comprehensive GitHub Actions Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      custom_param:
        description: 'Custom parameter for manual run'
        required: false
        default: 'default_value'

env:
  # Global environment variable accessible across all jobs
  GLOBAL_VAR: global_value

permissions:
  contents: write
  actions: read
  checks: read

jobs:

  matrix:
    name: job - run matrix
    runs-on: ubuntu-latest
    env:
      BUILD_ENV: build_value
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [1, 2]
      fail-fast: false # Continue testing other configurations if one fails
      max-parallel: 3
    steps:
      - name: print matrix variables
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Node Version: ${{ matrix.version }}"
      - name: print other variables
        run: |
          echo "Global Variable: $GLOBAL_VAR"
          echo "Build Environment Variable: $BUILD_ENV"
          echo "Actor: $GITHUB_ACTOR"
          echo "Repository: $GITHUB_REPOSITORY"
          echo "Event Name: $GITHUB_EVENT_NAME"

  reusable-workflow-1:
    name: job - call reusable-workflow-1 with parameters 1
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      param1: 'First reusable workflow call'
      param2: 'Additional context for call 1'
    secrets:
      API_SECRET: ${{ secrets.DEPLOY_API_KEY }}

  reusable-workflow-2:
    name: job - call reusable-workflow-1 with parameters 2
    uses: ./.github/workflows/reusable-workflow-1.yml
    with:
      param1: 'Second reusable workflow call'
      param2: 'Additional context for call 2'
    secrets:
      API_SECRET: ${{ secrets.DEPLOY_API_KEY }}

  reusable-action-1:
    name: job - call reusable action 1 with parameters 1
    runs-on: ubuntu-latest
    steps:
      - name: step - checkout code
        uses: actions/checkout@v3

      - name: step - call reusable action 1 with parameters 1
        uses: ./.github/actions/reusable-action-1
        with:
          name: "First Action Learner"

  reusable-action-2:
    name: job - call reusable action 1 with parameters 2
    runs-on: macos-latest
    steps:
      - name: step - checkout code
        uses: actions/checkout@v3

      - name: step - call reusable action 1 with parameters 2
        uses: ./.github/actions/reusable-action-1
        with:
          name: "Second Action Learner"

  clean-up:
    name: Cleanup Job
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: step - run cleanup scripts
        run: echo "cleaning up after workflow..."
